DROP TABLE IF EXISTS images CASCADE;
CREATE TABLE IF NOT EXISTS images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    data bytea NOT NULL,
    CONSTRAINT pk_image PRIMARY KEY (image_id)
);

DROP TABLE IF EXISTS usr CASCADE;
CREATE TABLE IF NOT EXISTS usr (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name varchar(250) NOT NULL,
    user_last_name varchar(250) NOT NULL,
    user_sur_name varchar(250) NOT NULL,
    birthday DATE NOT NULL,
    image_id BIGINT REFERENCES images(image_id),
    CONSTRAINT pk_usr PRIMARY KEY (user_id)
);

DROP TABLE IF EXISTS contact_information CASCADE;
CREATE TABLE IF NOT EXISTS contact_information (
    contact_information_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(250) NOT NULL,
    phone varchar(250) NOT NULL,
    user_id BIGINT REFERENCES usr(user_id),
    CONSTRAINT pk_contact_information PRIMARY KEY (contact_information_id)
);

DROP TABLE IF EXISTS  access_data CASCADE;
CREATE TABLE IF NOT EXISTS access_data (
                                           usr_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                           username varchar(50) unique,
    password varchar(250),
    enabled boolean default true NOT NULL
    );

DROP TABLE IF EXISTS authorities CASCADE ;
CREATE TABLE IF NOT EXISTS authorities (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           username varchar (250) references access_data(username),
    authority varchar(250)

    );






