version: '3.8'

services:
  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/msdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - "6541:5432"
    restart: on-failure
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=msdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}